apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy.edit
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: [ get,list,watch,create,update,patch,delete,deletecollection ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [ get,list,watch,create,update,patch,delete,deletecollection ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy.edit
  namespace: default
subjects:
- kind: User
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy.edit
  apiGroup: rbac.authorization.k8s.io
