apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy.view
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]  
    verbs: [ get, list, watch ]
  - apiGroups: [""]
    resources: ["pods"]  
    verbs: [ get, list, watch ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy.view
  namespace: default
subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy.view
  apiGroup: rbac.authorization.k8s.io
